# Week 1 Homework

In [1]:
import pandas as pd
import numpy as np

## Question 1
What's the version of NumPy that you installed?

In [2]:
np.__version__

'1.20.3'

In [3]:
pd.__version__

'1.4.1'

## Question 2
How many records are in the dataset?

In [4]:
data_df = pd.read_csv('data.csv')

In [5]:
data_df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [6]:
data_df.shape

(11914, 16)

In [7]:
print(f'Number of records: {data_df.shape[0]}')

Number of records: 11914


## Question 3
Who are the most frequent car manufacturers (top-3) according to the dataset?

In [10]:
data_df['Make'].unique()

array(['BMW', 'Audi', 'FIAT', 'Mercedes-Benz', 'Chrysler', 'Nissan',
       'Volvo', 'Mazda', 'Mitsubishi', 'Ferrari', 'Alfa Romeo', 'Toyota',
       'McLaren', 'Maybach', 'Pontiac', 'Porsche', 'Saab', 'GMC',
       'Hyundai', 'Plymouth', 'Honda', 'Oldsmobile', 'Suzuki', 'Ford',
       'Cadillac', 'Kia', 'Bentley', 'Chevrolet', 'Dodge', 'Lamborghini',
       'Lincoln', 'Subaru', 'Volkswagen', 'Spyker', 'Buick', 'Acura',
       'Rolls-Royce', 'Maserati', 'Lexus', 'Aston Martin', 'Land Rover',
       'Lotus', 'Infiniti', 'Scion', 'Genesis', 'HUMMER', 'Tesla',
       'Bugatti'], dtype=object)

In [11]:
data_df['Make'].value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

In [12]:
# top-3 car manufacturers
data_df['Make'].value_counts()[:3]

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

## Question 4
What's the number of unique Audi car models in the dataset?

In [13]:
type(data_df['Make'].value_counts())

pandas.core.series.Series

In [17]:
data_df.loc[data_df['Make'] == 'Audi']

Make Model  Year             Engine Fuel Type  Engine HP  \
17     Audi   100  1992             regular unleaded      172.0   
18     Audi   100  1992             regular unleaded      172.0   
19     Audi   100  1992             regular unleaded      172.0   
20     Audi   100  1992             regular unleaded      172.0   
21     Audi   100  1992             regular unleaded      172.0   
...     ...   ...   ...                          ...        ...   
10901  Audi   TTS  2016  premium unleaded (required)      292.0   
10902  Audi   TTS  2017  premium unleaded (required)      292.0   
11178  Audi    V8  1992             regular unleaded      276.0   
11179  Audi    V8  1993             regular unleaded      276.0   
11180  Audi    V8  1994             regular unleaded      276.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
17                  6.0            MANUAL  front wheel drive              4.0   
18                  6.0            MANUAL  front wheel drive              4.0   
19                  6.0         AUTOMATIC    all wheel drive              4.0   
20                  6.0            MANUAL  front wheel drive              4.0   
21                  6.0            MANUAL    all wheel drive              4.0   
...                 ...               ...                ...              ...   
10901               4.0  AUTOMATED_MANUAL    all wheel drive              2.0   
10902               4.0  AUTOMATED_MANUAL    all wheel drive              2.0   
11178               8.0         AUTOMATIC    all wheel drive              4.0   
11179               8.0         AUTOMATIC    all wheel drive              4.0   
11180               8.0         AUTOMATIC    all wheel drive              4.0   

                             Market Category Vehicle Size Vehicle Style  \
17                                    Luxury      Midsize         Sedan   
18                                    Luxury      Midsize         Sedan   
19                                    Luxury      Midsize         Wagon   
20                                    Luxury      Midsize         Sedan   
21                                    Luxury      Midsize         Sedan   
...                                      ...          ...           ...   
10901       Factory Tuner,Luxury,Performance      Compact         Coupe   
10902  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
11178                     Luxury,Performance      Midsize         Sedan   
11179                     Luxury,Performance      Midsize         Sedan   
11180                     Luxury,Performance      Midsize         Sedan   

       highway MPG  city mpg  Popularity   MSRP  
17              24        17        3105   2000  
18              24        17        3105   2000  
19              20        16        3105   2000  
20              24        17        3105   2000  
21              21        16        3105   2000  
...            ...       ...         ...    ...  
10901           27        23        3105  51900  
10902           27        23        3105  52500  
11178           18        13        3105   2000  
11179           18        13        3105   2149  
11180           18        13        3105   2239  

[328 rows x 16 columns]

In [89]:
data_df.loc[data_df['Make'] == 'Audi']['Model'].nunique()

34

## Question 5
How many columns in the dataset have missing values?

In [21]:
data_df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [22]:
print('5 columns have missing values')

5 columns have missing values


## Question 6
* Find the median value of "Engine Cylinders" column in the dataset.
* Next, calculate the most frequent value of the same "Engine Cylinders".
* Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
* Now, calculate the median value of "Engine Cylinders" once again.

In [25]:
round(data_df['Engine Cylinders'].mean(), 2)

5.63

In [27]:
data_df['Engine Cylinders'].value_counts()

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [34]:
eng_cyl_fillna = data_df['Engine Cylinders'].fillna(value=0)
eng_cyl_fillna

0        6.0
1        6.0
2        6.0
3        6.0
4        6.0
        ... 
11909    6.0
11910    6.0
11911    6.0
11912    6.0
11913    6.0
Name: Engine Cylinders, Length: 11914, dtype: float64

In [35]:
round(eng_cyl_fillna.mean(), 2)

5.61

In [36]:
if round(data_df['Engine Cylinders'].mean(), 2) - round(eng_cyl_fillna.mean(), 2) != 0:
    print('Changed')
else:
    print('Not changed')

Changed


## Question 7
* Select all the "Lotus" cars from the dataset.
* Select only columns "Engine HP", "Engine Cylinders".
* Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
* Get the underlying NumPy array. Let's call it X.
* Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
* Invert XTX.
* Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
* Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
* What's the value of the first element of w?

In [41]:
data_df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [44]:
for column in data_df.columns:
    if 'Lotus' in data_df[column].unique():
        print(column)
        print(data_df[column].unique())

Make
['BMW' 'Audi' 'FIAT' 'Mercedes-Benz' 'Chrysler' 'Nissan' 'Volvo' 'Mazda'
 'Mitsubishi' 'Ferrari' 'Alfa Romeo' 'Toyota' 'McLaren' 'Maybach'
 'Pontiac' 'Porsche' 'Saab' 'GMC' 'Hyundai' 'Plymouth' 'Honda'
 'Oldsmobile' 'Suzuki' 'Ford' 'Cadillac' 'Kia' 'Bentley' 'Chevrolet'
 'Dodge' 'Lamborghini' 'Lincoln' 'Subaru' 'Volkswagen' 'Spyker' 'Buick'
 'Acura' 'Rolls-Royce' 'Maserati' 'Lexus' 'Aston Martin' 'Land Rover'
 'Lotus' 'Infiniti' 'Scion' 'Genesis' 'HUMMER' 'Tesla' 'Bugatti']


/tmp/ipykernel_45651/685515711.py:2: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if 'Lotus' in data_df[column].unique():


In [46]:
lotus_df = data_df.loc[data_df.Make == 'Lotus']
lotus_df.head()

Make  Model  Year             Engine Fuel Type  Engine HP  \
3912  Lotus  Elise  2009  premium unleaded (required)      189.0   
3913  Lotus  Elise  2009  premium unleaded (required)      218.0   
3914  Lotus  Elise  2009  premium unleaded (required)      189.0   
3915  Lotus  Elise  2010  premium unleaded (required)      189.0   
3916  Lotus  Elise  2010  premium unleaded (required)      218.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   
3914               4.0            MANUAL  rear wheel drive              2.0   
3915               4.0            MANUAL  rear wheel drive              2.0   
3916               4.0            MANUAL  rear wheel drive              2.0   

              Market Category Vehicle Size Vehicle Style  highway MPG  \
3912  Exotic,High-Performance      Compact   Convertible           27   
3913  Exotic,High-Performance      Compact   Convertible           26   
3914  Exotic,High-Performance      Compact   Convertible           27   
3915  Exotic,High-Performance      Compact   Convertible           27   
3916  Exotic,High-Performance      Compact   Convertible           26   

      city mpg  Popularity   MSRP  
3912        21         613  43995  
3913        20         613  54990  
3914        21         613  47250  
3915        21         613  47250  
3916        20         613  54990

In [48]:
hp_cyl_lotus = lotus_df[['Engine HP', 'Engine Cylinders']]
hp_cyl_lotus.head()

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0

In [49]:
hp_cyl_lotus = hp_cyl_lotus.drop_duplicates()

In [50]:
hp_cyl_lotus.shape

(9, 2)

In [52]:
X = hp_cyl_lotus.values

In [53]:
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [54]:
X.T

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [58]:
XTX = np.matmul(X.T, X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [60]:
XTX_inv = np.linalg.inv(XTX) 
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [61]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [78]:
y.shape

(9,)

In [73]:
XTX_inv.shape

(2, 2)

In [72]:
X.T.shape

(2, 9)

In [79]:
w = np.dot(XTX_inv, X.T).dot(y)

In [80]:
w.shape

(2,)

In [81]:
w

array([  4.59494481, -63.56432501])

In [83]:
print(f'First element of w is {w[0]}')

First element of w is 4.594944810094579
