In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/ls/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'>

In [4]:
# creationg arrays
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [10]:
a = np.array([1, 2, 3, 4, 5, 7, 12])
a

array([ 1,  2,  3,  4,  5,  7, 12])

In [11]:
a[2]

3

In [12]:
a[2] = 10
a[2]

10

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [14]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [16]:
# multi dimentional arrays
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
M[0, 1]

2

In [20]:
M[0, 1] = 20
M

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [21]:
M[0]

array([ 1, 20,  3])

In [23]:
M[1] = [1, 1, 1]
M

array([[ 1, 20,  3],
       [ 1,  1,  1],
       [ 7,  8,  9]])

In [24]:
M[:, 1]

array([20,  1,  8])

In [25]:
M[:, 1] = [0, 1, 2]
M

array([[1, 0, 3],
       [1, 1, 1],
       [7, 2, 9]])

In [27]:
# randomly generated arrays
np.random.rand(5, 2)

array([[0.16241372, 0.46544283],
       [0.12004625, 0.10638499],
       [0.61721305, 0.49866327],
       [0.76300371, 0.09744602],
       [0.27596158, 0.08375189]])

In [29]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [30]:
np.random.seed(2)
np.random.randn(5, 2) # normal distribution

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [31]:
np.random.seed(2)
np.random.rand(5, 2) * 100

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [33]:
np.random.seed(2)
np.random.randint(low=5, high=100, size=(5, 2))

array([[45, 20],
       [77, 27],
       [48, 87],
       [80, 12],
       [39, 54]])

In [34]:
# element-wise operations
a = np.arange(5)

In [35]:
a

array([0, 1, 2, 3, 4])

In [36]:
a + 1

array([1, 2, 3, 4, 5])

In [39]:
b = 10 + ((a * 2) ** 2) / 0.23
b

array([ 10.        ,  27.39130435,  79.56521739, 166.52173913,
       288.26086957])

In [40]:
a + b

array([ 10.        ,  28.39130435,  81.56521739, 169.52173913,
       292.26086957])

In [41]:
a / b

array([0.        , 0.03650794, 0.02513661, 0.01801567, 0.01387632])

In [44]:
# comparison operations
print(a)
print(a >= 2)

[0 1 2 3 4]
[False False  True  True  True]


In [46]:
a

array([0, 1, 2, 3, 4])

In [47]:
b

array([ 10.        ,  27.39130435,  79.56521739, 166.52173913,
       288.26086957])

In [50]:
a > b

array([False, False, False, False, False])

In [51]:
a[a > b] # return a array of indexes 

array([], dtype=int64)

In [53]:
# summarizing operations
a

array([0, 1, 2, 3, 4])

In [54]:
a.min()

0

In [55]:
a.sum()

10

In [57]:
a.mean()

2.0

In [58]:
a.std()

1.4142135623730951