In [1]:
import numpy as np

In [2]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

In [3]:
# element-wise multiplication
u * v

array([ 2,  0,  0, 12])

In [4]:
u * 2

array([ 4,  8, 10, 12])

**dot product**
$$ \sum_{i=0}^{n-1} u_iv_i $$

In [5]:
# dot product
def dot_product(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [6]:
dot_product(u, v)

14.0

In [7]:
u.dot(v)

14

In [8]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]])

In [10]:
U.shape[1] 

4

In [9]:
v = np.array([1, 0.5, 2, 1])

In [11]:
v.shape[0]

4

In [14]:
# U_34 x v_41 -> Uv_31
def matrix_vec_multi(U, v):
    assert U.shape[1] == v.shape[0]
    
    n_rows = U.shape[0]
    
    result = np.zeros(n_rows)
    
    for i in range(n_rows):
        result[i] = U[i].dot(v)
        
    return result

In [15]:
matrix_vec_multi(U, v)

array([20. ,  6. ,  8.5])

In [16]:
# matrix multiplication
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]])

In [23]:
V.shape[0]

4

In [24]:
for i in range(V.shape[1]):
    print(U[:, i].shape)

(3,)
(3,)
(3,)


In [20]:
def matrix_multi(U, V):
    assert U.shape[1] == V.shape[0]
    
    n_rows = U.shape[0]
    n_cols = V.shape[1]
    
    result = np.zeros((n_rows, n_cols))
    
    for i in range(n_cols):
        vi = U[:, i]
        Uvi = matrix_vec_multi(U, vi)
        result[:, i] = Uvi
        
    return result

In [ ]:
matrix_multi(U, V)

In [27]:
# identity matrix: diagonal has 1's and zeros everywhere
n = 5
I = np.eye(n)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
Vs = V[:3, :]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [32]:
# inverse matrix
matrix_multi(np.linalg.inv(Vs), Vs)

array([[ 1.        , -0.66666667, -1.33333333],
       [ 0.        ,  1.33333333, -0.66666667],
       [ 0.        , -1.33333333,  1.        ]])